lang: ru
project:
  type: website
  output-dir: _site
  render: [index.qmd]
  resources: [artifacts/**]
website:
  title: Печатные задания
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-course-print
  repo-subdir: examples/paper
  repo-actions: [source]
  repo-branch: demo-20261007-ru1
format: html
course:
  id: demo-paper
profile:
  default: full
  group: [[student, full]]
